In [93]:
import pandas as pd

In [214]:
df3 = pd.read_csv('df3.csv')
df3

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Cho...,Fantasy,Young Adult,326,1988,Fiction
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction
4,155651,Nancy Baker,/author/show/155651.Nancy_Baker,USA and Canada,3.77,https://www.goodreads.com/book/show/266600.Kis...,266600,Kiss of the Vampire,Paranormal,Horror,278,1993,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7226,12020546,S.D. Wasley,/author/show/12020546.S_D_Wasley,Oceania,4.05,https://www.goodreads.com/book/show/24474924-t...,24474924,The Seventh,Young Adult,Fantasy,262,2015,Fiction
7227,8386732,Victoria Zak,/author/show/8386732.Victoria_Zak,Unknown,4.22,https://www.goodreads.com/book/show/23552511-h...,23552511,Highland Storm,Romance,Romance,232,2015,Fiction
7228,108007,Dakota Cassidy,/author/show/108007.Dakota_Cassidy,Unknown,3.82,https://www.goodreads.com/book/show/24614174-g...,24614174,Gotta Have Faith,Fantasy,Romance,72,2015,Fiction
7229,6543639,Krystal Shannan,/author/show/6543639.Krystal_Shannan,USA and Canada,3.73,https://www.goodreads.com/book/show/35892811-m...,35892811,My Viking Vampire,Fantasy,Paranormal,237,2014,Fiction
7230,5246010,Bryce Evans,/author/show/5246010.Bryce_Evans,Unknown,3.89,https://www.goodreads.com/book/show/17187320-t...,17187320,The Trinity,Fantasy,Paranormal,222,2012,Fiction

In [215]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7231 entries, 0 to 7230
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   author_id            7231 non-null   object
 1   author_name          7231 non-null   object
 2   author_page_url      7231 non-null   object
 3   birthplace           7231 non-null   object
 4   book_average_rating  7231 non-null   object
 5   book_fullurl         7231 non-null   object
 6   book_id              7231 non-null   object
 7   book_title           7231 non-null   object
 8   genre_1              7231 non-null   object
 9   genre_2              7231 non-null   object
 10  pages                7231 non-null   object
 11  year_publication     7142 non-null   object
 12  fiction_nonfiction   7231 non-null   object
dtypes: object(13)
memory usage: 734.5+ KB

In [216]:
df3['genre_1'].unique()

array(['Mystery', 'Romance', 'Fantasy', 'Young Adult', 'Paranormal',
       'Historical', 'Science Fiction', 'Fiction', 'Classics',
       'New Adult', 'Contemporary', 'Womens Fiction', 'Horror', 'Humor',
       'Sequential Art', 'Lgbt', 'Sports and Games', 'War', 'Dark',
       'Childrens', 'Christian Fiction', 'Warfare', 'Adult Fiction',
       'Short Stories', 'Animals', 'Erotica', 'Crime', 'Poetry', 'Novels',
       'Thriller', 'Music', 'Mythology', 'Anthologies', 'Death',
       'Magical Realism', 'Christian', 'Realistic Fiction', 'Suspense',
       'Category Romance', 'Science Fiction Fantasy', 'LGBT', 'Cultural',
       'Literary Fiction', 'Novella', 'Asian Literature', 'Health',
       'Biblical Fiction', 'Adventure', 'Literature', 'Polyamorous',
       'Westerns', 'Dark Fantasy', 'Comics', 'Drama', 'Nonfiction',
       'Manga', 'Novel'], dtype=object)

In [217]:
df3.loc[df3['genre_1'] == 'Lgbt', 'genre_1'] = 'LGBT'

In [218]:
df3.loc[df3['genre_1'] == 'Sequential Art', 'genre_1'] = 'Comics, Graphic Novels & Manga'
df3.loc[df3['genre_1'] == 'Comics', 'genre_1'] = 'Comics, Graphic Novels & Manga'
df3.loc[df3['genre_1'] == 'Manga', 'genre_1'] = 'Comics, Graphic Novels & Manga'

In [219]:
df3 = df3.drop(df3[df3['genre_1'] == 'Nonfiction'].index)

In [220]:
df3.loc[df3['genre_1'] == 'Category Romance', 'genre_1'] = 'Romance'

In [221]:
df3.loc[df3['genre_1'] == 'Warfare', 'genre_1'] = 'Erotica'

In [222]:
df3.loc[df3['genre_1'] == 'Biblical Fiction', 'genre_1'] = 'Christian Fiction'

In [223]:
df3 = df3.drop(df3[df3['genre_1'] == 'Asian Literature'].index)

In [227]:
df3.loc[df3['genre_1'] == 'Biblical Fiction']

Empty DataFrame
Columns: [author_id, author_name, author_page_url, birthplace, book_average_rating, book_fullurl, book_id, book_title, genre_1, genre_2, pages, year_publication, fiction_nonfiction]
Index: []

In [228]:
df3.loc[df3['genre_1'] == 'Christian', 'genre_1'] = 'Christian Fiction'

In [229]:
df3.loc[df3['genre_1'] == 'Adult Fiction', 'genre_1'] = 'Erotica'

In [230]:
df3 = df3.drop(df3[df3['genre_1'] == 'Science Fiction Fantasy'].index)

In [231]:
df3 = df3.drop(df3[df3['genre_1'] == 'Dark Fantasy'].index)

In [232]:
df3 = df3.drop(df3[df3['genre_1'] == 'Novel'].index)
df3 = df3.drop(df3[df3['genre_1'] == 'Novels'].index)

In [233]:
df3.loc[df3['genre_1'] == 'Thriller', 'genre_1'] = 'Thriller & Suspense'
df3.loc[df3['genre_1'] == 'Suspense', 'genre_1'] = 'Thriller & Suspense'

In [234]:
df3 = df3.drop(df3[df3['genre_1'] == 'Westerns'].index)

In [235]:
df3 = df3.drop(df3[df3['genre_1'] == 'Literature'].index)

In [236]:
def cleaning_polyamorous(df, col1, col2,):
    conditions1 = (df[col1] == 'Polyamorous') & (df[col2] == 'Fantasy')
    df.loc[conditions1, col1] = 'Fantasy'

    conditions2 = (df[col1] == 'Polyamorous') & (df[col2] == 'Romance')
    df.loc[conditions2, col1] = 'Romance'

In [237]:
cleaning_polyamorous(df3, 'genre_1', 'genre_2')

In [238]:
df3 = df3.drop(df3[df3['genre_1'] == 'Health'].index)

In [239]:
df3 = df3.drop(df3[df3['genre_1'] == 'Novella'].index)

In [240]:
df3 = df3.drop(df3[df3['genre_1'] == 'Literary Fiction'].index)

In [241]:
df3 = df3.drop(df3[df3['genre_1'] == 'Cultural'].index)

In [242]:
def cleaning_realistic_fiction(df, col1, col2,):
    conditions1 = (df[col1] == 'Realistic Fiction') & (df[col2] == 'Young Adult')
    df.loc[conditions1, col1] = 'Young Adult'

    conditions2 = (df[col1] == 'Realistic Fiction') & (df[col2] == 'Romance')
    df.loc[conditions2, col1] = 'Romance'
    
    conditions3 = (df[col1] == 'Realistic Fiction') & (df[col2] == 'Childrens')
    df.loc[conditions3, col1] = 'Childrens'

In [243]:
cleaning_realistic_fiction(df3, 'genre_1', 'genre_2')

In [244]:
df3 = df3.drop(df3[df3['genre_1'] == 'Realistic Fiction'].index)

In [245]:
def cleaning_women_fiction(df, col1, col2,):
    conditions1 = (df[col1] == 'Womens Fiction') & (df[col2] == 'Mystery')
    df.loc[conditions1, col1] = 'Mystery'

    conditions2 = (df[col1] == 'Womens Fiction') & (df[col2] == 'Romance')
    df.loc[conditions2, col1] = 'Romance'

In [246]:
cleaning_women_fiction(df3, 'genre_1', 'genre_2')

In [247]:
def cleaning_contemporary(df, col1, col2,):
    conditions1 = (df[col1] == 'Contemporary') & (df[col2] == 'Young Adult')
    df.loc[conditions1, col1] = 'Young Adult'

    conditions2 = (df[col1] == 'Contemporary') & (df[col2].isin(['Romance', 'New Adult']))
    df.loc[conditions2, col1] = 'Romance'
    
    conditions3 = (df[col1] == 'Contemporary') & (df[col2].isin(['LGBT', "Lgbt"]))
    df.loc[conditions3, col1] = 'LGBT'
    
    conditions4 = (df[col1] == 'Contemporary') & (df[col2] == 'Drama')
    df.loc[conditions4, col1] = 'Drama'
    
    conditions5 = (df[col1] == 'Contemporary') & (df[col2] == 'Short Stories')
    df.loc[conditions5, col1] = 'Short Stories'
    
    conditions6 = (df[col1] == 'Contemporary') & (df[col2] == 'Adult')
    df.loc[conditions6, col1] = 'Erotica'

In [248]:
cleaning_contemporary(df3, 'genre_1', 'genre_2')

In [249]:
df3 = df3.drop(df3[df3['genre_1'] == 'Contemporary'].index)

In [250]:
df3.loc[df3['genre_1'] == 'War', 'genre_1'] = 'Romance'

In [251]:
df3.loc[df3['book_id'] == '18112803', 'genre_1'] = 'LGBT'

In [252]:
def cleaning_sports(df, col1, col2,):
    conditions1 = (df[col1] == 'Sports and Games') & (df[col2].isin(['Romance', 'New Adult', 'Contemporary Romance', 'Sports']))
    df.loc[conditions1, col1] = 'Romance'

In [253]:
cleaning_sports(df3, 'genre_1', 'genre_2')

In [280]:
df3['genre_1'].unique()

array(['Mystery', 'Romance', 'Fantasy', 'Young Adult', 'Historical',
       'Science Fiction', 'Classics', 'New Adult', 'Horror',
       'Womens Fiction', 'Comics, Graphic Novels & Manga', 'LGBT',
       'Childrens', 'Christian Fiction', 'Erotica', 'Crime',
       'Thriller & Suspense', 'Drama', 'Adventure'], dtype=object)

In [255]:
df3.loc[df3['genre_1'] == 'Music', 'genre_1'] = 'Romance'

In [256]:
df3 = df3.drop(df3[df3['genre_1'] == 'Anthologies'].index)

In [257]:
df3 = df3.drop(df3[df3['genre_1'] == 'Animals'].index)

In [258]:
df3.loc[df3['genre_1'] ==  'Mythology', 'genre_1'] = 'Fantasy'

In [259]:
def cleaning_magical(df, col1, col2,):
    conditions1 = (df[col1] == 'Magical Realism') & (df[col2] == 'Fantasy')
    df.loc[conditions1, col1] = 'Fantasy'

    conditions2 = (df[col1] == 'Magical Realism') & (df[col2] == 'Childrens')
    df.loc[conditions2, col1] = 'Childrens'

cleaning_magical(df3, 'genre_1', 'genre_2')

In [260]:
df3 = df3.drop(df3[df3['genre_1'] == 'Death'].index)

In [261]:
df3 = df3.drop(df3[df3['genre_1'] == 'Short Stories'].index)

In [262]:
df3 = df3.drop(df3[df3['genre_1'] == 'Poetry'].index)

In [263]:
df3 = df3.drop(df3[df3['genre_1'] == 'Dark'].index)

In [264]:
df3.loc[df3['genre_1'] ==  'Thriller', 'genre_1'] = 'Thriller & Suspense'

In [265]:
def cleaning_dark(df, col1, col2,):
    conditions1 = (df[col1] == 'Dark') & (df[col2] == 'Romance')
    df.loc[conditions1, col1] = 'Romance'

    conditions2 = (df[col1] == 'Dark') & (df[col2].isin(['Erotica', 'Adult Fiction']))
    df.loc[conditions2, col1] = 'Erotica'
    
    conditions3 = (df[col1] == 'Dark') & (df[col2] == 'Mystery')
    df.loc[conditions3, col1] = 'Thriller'
    
    conditions4 = (df[col1] == 'Dark') & (df[col2] == 'Fantasy')
    df.loc[conditions4, col1] = 'Fantasy'
    
    conditions5 = (df[col1] == 'Dark') & (df[col2] == 'Young Adult')
    df.loc[conditions5, col1] = 'Young Adult'

cleaning_dark(df3, 'genre_1', 'genre_2')

In [266]:
df3 = df3.drop(df3[df3['genre_1'] == 'Paranormal'].index)

In [267]:
def cleaning_paranormal(df, col1, col2,):
    conditions1 = (df[col1] == 'Paranormal') & (df[col2] == 'Romance')
    df.loc[conditions1, col1] = 'Romance'

    conditions2 = (df[col1] == 'Paranormal') & (df[col2] == 'Fantasy')
    df.loc[conditions2, col1] = 'Fantasy'
    
    conditions3 = (df[col1] == 'Paranormal') & (df[col2] == 'Young Adult')
    df.loc[conditions3, col1] = 'Young Adult'
    
    conditions4 = (df[col1] == 'Paranormal') & (df[col2] == 'Erotica')
    df.loc[conditions4, col1] = 'Erotica'

cleaning_paranormal(df3, 'genre_1', 'genre_2')

In [268]:
df3 = df3.drop(df3[df3['genre_1'] == 'Humor'].index)

In [273]:
def cleaning_fiction(df, col1, col2,):
    conditions1 = (df[col1] == 'Fiction') & (df[col2] == 'Science Fiction')
    df.loc[conditions1, col1] = 'Science Fiction'

    conditions2 = (df[col1] == 'Fiction') & (df[col2] == 'Historical')
    df.loc[conditions2, col1] = 'Historical'
    
    conditions3 = (df[col1] == 'Fiction') & (df[col2] == 'Classics')
    df.loc[conditions3, col1] = 'Classics'
    
    conditions3 = (df[col1] == 'Fiction') & (df[col2] == 'Mystery')
    df.loc[conditions3, col1] = 'Mystery'
    
    conditions4 = (df[col1] == 'Fiction') & (df[col2].isin(['Contemporary', 'Womens Fiction', 'Cultural', 'Short Stories', 'American', 'Animals', 'Psychology', 'Literary Fiction', 'See top shelvesâ€¦']))
    df.loc[conditions4, col1] = 'Delete'
    
    conditions5 = (df[col1] == 'Fiction') & (df[col2] == 'Romance')
    df.loc[conditions5, col1] = 'Romance'
    
    conditions6 = (df[col1] == 'Fiction') & (df[col2] == 'Childrens')
    df.loc[conditions6, col1] = 'Childrens'
    
    conditions7 = (df[col1] == 'Fiction') & (df[col2].isin(['Fantasy', 'Magical Realism', 'Paranormal']))
    df.loc[conditions7, col1] = 'Fantasy'
    
    conditions8 = (df[col1] == 'Fiction') & (df[col2] == 'Young Adult')
    df.loc[conditions8, col1] = 'Young Adult'
    
    conditions9 = (df[col1] == 'Fiction') & (df[col2] == 'Horror')
    df.loc[conditions9, col1] = 'Horror'
    
    conditions9 = (df[col1] == 'Fiction') & (df[col2].isin(['Christian Fiction', 'Christian']))
    df.loc[conditions9, col1] = 'Christian Fiction'
    
    conditions10 = (df[col1] == 'Fiction') & (df[col2].isin(['Thriller', 'Suspense']))
    df.loc[conditions10, col1] = 'Thriller & Suspense'
    
    conditions11 = (df[col1] == 'Fiction') & (df[col2].isin(['LGBT', 'Lgbt']))
    df.loc[conditions11, col1] = 'LGBT'
    
    conditions12 = (df[col1] == 'Fiction') & (df[col2] == 'Drama')
    df.loc[conditions12, col1] = 'Drama'
    
    conditions13 = (df[col1] == 'Fiction') & (df[col2] == 'Sequential Art')
    df.loc[conditions13, col1] = 'Comics, Graphic Novels & Manga'

cleaning_fiction(df3, 'genre_1', 'genre_2')

In [275]:
df3 = df3.drop(df3[df3['genre_1'] == 'Fiction'].index)

In [279]:
df3 = df3.drop(df3[df3['genre_1'] == 'Delete'].index)

In [282]:
df3 = df3.drop(df3[df3['genre_1'] == 'Womens Fiction'].index)

In [287]:
df3.groupby(['genre_1']).count()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_2,pages,year_publication,fiction_nonfiction
genre_1,,,,,,,,,,,,
Adventure,7,7,7,7,7,7,7,7,7,7,7,7
Childrens,131,131,131,131,131,131,131,131,131,131,131,131
Christian Fiction,124,124,124,124,124,124,124,124,124,124,121,124
Classics,103,103,103,103,103,103,103,103,103,103,103,103
"Comics, Graphic Novels & Manga",133,133,133,133,133,133,133,133,133,133,131,133
Crime,4,4,4,4,4,4,4,4,4,4,4,4
Drama,3,3,3,3,3,3,3,3,3,3,3,3
Erotica,145,145,145,145,145,145,145,145,145,145,144,145
Fantasy,1318,1318,1318,1318,1318,1318,1318,1318,1318,1318,1300,1318
Historical,694,694,694,694,694,694,694,694,694,694,690,694
Horror,92,92,92,92,92,92,92,92,92,92,92,92
LGBT,73,73,73,73,73,73,73,73,73,73,72,73
Mystery,340,340,340,340,340,340,340,340,340,340,336,340
New Adult,175,175,175,175,175,175,175,175,175,175,175,175
Romance,1954,1954,1954,1954,1954,1954,1954,1954,1954,1954,1924,1954
Science Fiction,226,226,226,226,226,226,226,226,226,226,219,226
Thriller & Suspense,56,56,56,56,56,56,56,56,56,56,56,56
Young Adult,979,979,979,979,979,979,979,979,979,979,971,979

In [288]:
df3 = df3.drop(df3[df3['genre_1'] == 'Adventure'].index)
df3 = df3.drop(df3[df3['genre_1'] == 'Crime'].index)
df3 = df3.drop(df3[df3['genre_1'] == 'Drama'].index)

In [293]:
df3.loc[df3['genre_1'] == 'New Adult']

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction
842,7105371,Leah Raeder,/author/show/7105371.Leah_Raeder,Asia,3.75,https://www.goodreads.com/book/show/18829666-b...,18829666,Black Iris,New Adult,Contemporary,371,2015,Fiction
2462,7215619,Aurora Rose Reynolds,/author/show/7215619.Aurora_Rose_Reynolds,USA and Canada,4.14,https://www.goodreads.com/book/show/18341046-u...,18341046,Until November,New Adult,Contemporary,291,2013,Fiction
3438,7023103,M.J. Fields,/author/show/7023103.M_J_Fields,USA and Canada,4.45,https://www.goodreads.com/book/show/17700271-t...,17700271,True Love,New Adult,Contemporary,379,2013,Fiction
4224,6522939,Carla J. Hanna,/author/show/6522939.Carla_J_Hanna,USA and Canada,4.75,https://www.goodreads.com/book/show/17866941-s...,17866941,Starlet's Light,New Adult,See top shelvesâ€¦,294,2013,Fiction
5825,7581125,K.L. Shandwick,/author/show/7581125.K_L_Shandwick,Europe,4.17,https://www.goodreads.com/book/show/22707078-l...,22707078,Love with Every Beat,New Adult,See top shelvesâ€¦,479,2014,Fiction
6075,1254833,R.L. Griffin,/author/show/1254833.R_L_Griffin,USA and Canada,4.32,https://www.goodreads.com/book/show/17840262-t...,17840262,Tension,New Adult,Dark,280,2013,Fiction
6087,7328358,Rochelle Paige,/author/show/7328358.Rochelle_Paige,USA and Canada,3.71,https://www.goodreads.com/book/show/19543263-p...,19543263,Push the Envelope,New Adult,Academic,180,2013,Fiction
6408,7057541,Karli Perrin,/author/show/7057541.Karli_Perrin,Europe,3.7,https://www.goodreads.com/book/show/18757146-t...,18757146,The Gift,New Adult,Contemporary,38,2013,Fiction
6638,6982524,Stephanie Witter,/author/show/6982524.Stephanie_Witter,Asia,3.81,https://www.goodreads.com/book/show/17979646-p...,17979646,Patch Up,New Adult,Sociology,296,2013,Fiction

In [292]:
def cleaning_new_adult(df, col1, col2,):
    conditions1 = (df[col1] == 'New Adult') & (df[col2] == 'Romance')
    df.loc[conditions1, col1] = 'Romance'

    conditions2 = (df[col1] == 'New Adult') & (df[col2] == 'Fantasy')
    df.loc[conditions2, col1] = 'Fantasy'
    
    conditions3 = (df[col1] == 'New Adult') & (df[col2] == 'Science Fiction')
    df.loc[conditions3, col1] = 'Science Fiction'
    
    conditions4 = (df[col1] == 'New Adult') & (df[col2] == 'Mystery')
    df.loc[conditions4, col1] = 'Mystery'
    
    conditions5 = (df[col1] == 'New Adult') & (df[col2] == 'Young Adult')
    df.loc[conditions5, col1] = 'Young Adult'
    
cleaning_new_adult(df3, 'genre_1', 'genre_2')

In [294]:
df3 = df3.drop(df3[df3['genre_1'] == 'New Adult'].index)

In [295]:
df3.groupby(['genre_1']).count()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_2,pages,year_publication,fiction_nonfiction
genre_1,,,,,,,,,,,,
Childrens,131,131,131,131,131,131,131,131,131,131,131,131
Christian Fiction,124,124,124,124,124,124,124,124,124,124,121,124
Classics,103,103,103,103,103,103,103,103,103,103,103,103
"Comics, Graphic Novels & Manga",133,133,133,133,133,133,133,133,133,133,131,133
Erotica,145,145,145,145,145,145,145,145,145,145,144,145
Fantasy,1322,1322,1322,1322,1322,1322,1322,1322,1322,1322,1304,1322
Historical,694,694,694,694,694,694,694,694,694,694,690,694
Horror,92,92,92,92,92,92,92,92,92,92,92,92
LGBT,73,73,73,73,73,73,73,73,73,73,72,73
Mystery,341,341,341,341,341,341,341,341,341,341,337,341
Romance,2113,2113,2113,2113,2113,2113,2113,2113,2113,2113,2083,2113
Science Fiction,227,227,227,227,227,227,227,227,227,227,220,227
Thriller & Suspense,56,56,56,56,56,56,56,56,56,56,56,56
Young Adult,980,980,980,980,980,980,980,980,980,980,972,980

In [296]:
df3.to_csv('df3_clean.csv', index=False)

In [37]:
df3 = pd.read_csv('df3_clean.csv')
df3.head()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Cho...,Fantasy,Young Adult,326,1988,Fiction
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction
4,274533,Simone Elkeles,/author/show/274533.Simone_Elkeles,USA and Canada,4.01,https://www.goodreads.com/book/show/544424.Lea...,544424,Leaving Paradise,Young Adult,Romance,303,2007,Fiction

In [38]:
df3.isna().sum()

author_id               0
author_name             0
author_page_url         0
birthplace              0
book_average_rating     0
book_fullurl            0
book_id                 0
book_title              0
genre_1                 0
genre_2                 0
pages                   0
year_publication       78
fiction_nonfiction      0
dtype: int64

In [39]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6534 entries, 0 to 6533
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   author_id            6534 non-null   object
 1   author_name          6534 non-null   object
 2   author_page_url      6534 non-null   object
 3   birthplace           6534 non-null   object
 4   book_average_rating  6534 non-null   object
 5   book_fullurl         6534 non-null   object
 6   book_id              6534 non-null   object
 7   book_title           6534 non-null   object
 8   genre_1              6534 non-null   object
 9   genre_2              6534 non-null   object
 10  pages                6534 non-null   object
 11  year_publication     6456 non-null   object
 12  fiction_nonfiction   6534 non-null   object
dtypes: object(13)
memory usage: 663.7+ KB

In [40]:
df3.dropna(inplace=True)

In [41]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6456 entries, 0 to 6533
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   author_id            6456 non-null   object
 1   author_name          6456 non-null   object
 2   author_page_url      6456 non-null   object
 3   birthplace           6456 non-null   object
 4   book_average_rating  6456 non-null   object
 5   book_fullurl         6456 non-null   object
 6   book_id              6456 non-null   object
 7   book_title           6456 non-null   object
 8   genre_1              6456 non-null   object
 9   genre_2              6456 non-null   object
 10  pages                6456 non-null   object
 11  year_publication     6456 non-null   object
 12  fiction_nonfiction   6456 non-null   object
dtypes: object(13)
memory usage: 706.1+ KB

In [42]:
df3.to_csv('df3_clean2.csv', index=False)

In [43]:
df3['birthplace'].unique()

array(['USA and Canada', 'Unknown', 'Europe', 'Latin America', 'Oceania',
       'Africa', 'Asia', 'Fantasy'], dtype=object)

In [44]:
df3 = df3.drop(df3[df3['birthplace'] == 'Fantasy'].index)

In [45]:
df3['birthplace'].unique()

array(['USA and Canada', 'Unknown', 'Europe', 'Latin America', 'Oceania',
       'Africa', 'Asia'], dtype=object)

In [77]:
df3['year_publication'].unique()

array(['2000', '2016', '1988', '2012', '2007', '2006', '2010', '2014',
       '2013', '1987', '2011', '1993', '1974', '2002', '1957', '1992',
       '2003', '2009', '1997', '1938', '1813', '1868', '1943', '1963',
       '1989', '2001', '2008', '2005', '2004', '1936', '2015', '1995',
       '1980', '1994', '1981', '1982', '1970', '1905', '1976', '1983',
       '1977', '1986', '1962', '2018', '1999', '2017', '1967', '1918',
       '1978', '1937', '1998', '1818', '1847', '1960', '1961', '1990',
       '1996', '1949', '1935', '1985', '1944', '1954', '1947', '1945',
       '1908', '1973', '1972', '1877', '1959', '1991', '1922', '2019',
       '1984', '1927', '1931', '1934', '1975', '1923', '1930', '1955',
       '1942', '1920', '1855', '1952', '1979', '1964', '1880', '1892',
       '1871', '1968', '1932', '1899', '1848', '1925', '1948', '1940',
       '1950', '1956', '1951', '1911', '1965', '1929', '1966', '1008',
       '1971', '1939', '1958', '1953', '1862', '1797', '1900', '1811',
       '1926', '1969', '1928', '1912', '1817', '1853', '1924', '1913',
       '1901', '1921', '1902', '1903', '1906', '1946', '1778', '1916',
       '1801', '1897', '1865', '1941'], dtype=object)

In [47]:
df3.loc[df3['year_publication'] == '19th', 'year_publication'] = '2019'

In [76]:
df3.loc[df3['year_publication'] == '0'] # Decided to check manually for the release dates of those books, since they are not so many
# Dropping the 4 that I could not find a release date:

df3 = df3.drop(df3[df3['year_publication'] == '0'].index)

In [49]:
df3.loc[df3['book_id'] == '307791', 'year_publication'] = '2003'

In [52]:
df3.loc[df3['book_id'] == '30236962', 'year_publication'] = '2005'

In [64]:
df3.loc[df3['book_id'] == '18333130', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '1814627', 'year_publication'] = '1997'
df3.loc[df3['book_id'] == '43448', 'year_publication'] = '1979'
df3.loc[df3['book_id'] == '40362474', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '6202556', 'year_publication'] = '2009'
df3.loc[df3['book_id'] == '18329942', 'year_publication'] = '2013'
df3.loc[df3['book_id'] == '822392', 'year_publication'] = '1951'
df3.loc[df3['book_id'] == '5981262', 'year_publication'] = '2009'

In [67]:
df3.loc[df3['book_id'] == '18045891', 'year_publication'] = '2006'
df3.loc[df3['book_id'] == '141452', 'year_publication'] = '1988'
df3.loc[df3['book_id'] == '21922122', 'year_publication'] = '2014'
df3.loc[df3['book_id'] == '473870', 'year_publication'] = '1993'
df3.loc[df3['book_id'] == '6340471', 'year_publication'] = '2009'
df3.loc[df3['book_id'] == '595911', 'year_publication'] = '2004'
df3.loc[df3['book_id'] == '6406946', 'year_publication'] = '2005'
df3.loc[df3['book_id'] == '1499952', 'year_publication'] = '1912'

In [70]:
df3.loc[df3['book_id'] == '2039223', 'year_publication'] = '2008'
df3.loc[df3['book_id'] == '3236819', 'year_publication'] = '2006'
df3.loc[df3['book_id'] == '15717280', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '1040935', 'year_publication'] = '2005'
df3.loc[df3['book_id'] == '578190', 'year_publication'] = '1981'
df3.loc[df3['book_id'] == '6381830', 'year_publication'] = '2008'
df3.loc[df3['book_id'] == '3236813', 'year_publication'] = '2006'

In [72]:
df3.loc[df3['book_id'] == '13422422', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '35082747', 'year_publication'] = '2015'
df3.loc[df3['book_id'] == '13613254', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '8164754', 'year_publication'] = '2009'
df3.loc[df3['book_id'] == '13575706', 'year_publication'] = '2012'
df3.loc[df3['book_id'] == '76706', 'year_publication'] = '1993'
df3.loc[df3['book_id'] == '11929846', 'year_publication'] = '2011'

In [74]:
df3.loc[df3['book_id'] == '857657', 'year_publication'] = '2007'
df3.loc[df3['book_id'] == '1680502', 'year_publication'] = '2007'
df3.loc[df3['book_id'] == '315882', 'year_publication'] = '2007'
df3.loc[df3['book_id'] == '6064286', 'year_publication'] = '2008'

In [79]:
df3['period_publication'] = df3['year_publication']

In [88]:
def period(df, col1, col2):
    df[col1] = pd.to_numeric(df[col1], errors='coerce')
    conditions1 = (df[col1] > 2000)
    df.loc[conditions1, col2] = '21st century'
    conditions2 = (df[col1] <= 2000)
    df.loc[conditions2, col2] = '20th century or before'

In [89]:
period(df3, 'year_publication', 'period_publication')
df3.head()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,period_publication
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction,20th century or before
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction,21st century
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Cho...,Fantasy,Young Adult,326,1988,Fiction,20th century or before
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction,21st century
4,274533,Simone Elkeles,/author/show/274533.Simone_Elkeles,USA and Canada,4.01,https://www.goodreads.com/book/show/544424.Lea...,544424,Leaving Paradise,Young Adult,Romance,303,2007,Fiction,21st century

In [90]:
df3['period_publication'].unique()

array(['20th century or before', '21st century'], dtype=object)

In [91]:
df3.reset_index(drop=True)

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,period_publication
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction,20th century or before
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction,21st century
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Cho...,Fantasy,Young Adult,326,1988,Fiction,20th century or before
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction,21st century
4,274533,Simone Elkeles,/author/show/274533.Simone_Elkeles,USA and Canada,4.01,https://www.goodreads.com/book/show/544424.Lea...,544424,Leaving Paradise,Young Adult,Romance,303,2007,Fiction,21st century
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6436,12020546,S.D. Wasley,/author/show/12020546.S_D_Wasley,Oceania,4.05,https://www.goodreads.com/book/show/24474924-t...,24474924,The Seventh,Young Adult,Fantasy,262,2015,Fiction,21st century
6437,8386732,Victoria Zak,/author/show/8386732.Victoria_Zak,Unknown,4.22,https://www.goodreads.com/book/show/23552511-h...,23552511,Highland Storm,Romance,Romance,232,2015,Fiction,21st century
6438,108007,Dakota Cassidy,/author/show/108007.Dakota_Cassidy,Unknown,3.82,https://www.goodreads.com/book/show/24614174-g...,24614174,Gotta Have Faith,Fantasy,Romance,72,2015,Fiction,21st century
6439,6543639,Krystal Shannan,/author/show/6543639.Krystal_Shannan,USA and Canada,3.73,https://www.goodreads.com/book/show/35892811-m...,35892811,My Viking Vampire,Fantasy,Paranormal,237,2014,Fiction,21st century
6440,5246010,Bryce Evans,/author/show/5246010.Bryce_Evans,Unknown,3.89,https://www.goodreads.com/book/show/17187320-t...,17187320,The Trinity,Fantasy,Paranormal,222,2012,Fiction,21st century

In [92]:
df3.to_csv('df3_final.csv', index=False)

In [95]:
df3 = pd.read_csv('df3_final.csv')
df3.groupby(['genre_1']).count()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_2,pages,year_publication,fiction_nonfiction,period_publication
genre_1,,,,,,,,,,,,,
Childrens,130,130,130,130,130,130,130,130,130,130,130,130,130
Christian Fiction,121,121,121,121,121,121,121,121,121,121,121,121,121
Classics,103,103,103,103,103,103,103,103,103,103,103,103,103
"Comics, Graphic Novels & Manga",130,130,130,130,130,130,130,130,130,130,130,130,130
Erotica,144,144,144,144,144,144,144,144,144,144,144,144,144
Fantasy,1291,1291,1291,1291,1291,1291,1291,1291,1291,1291,1291,1291,1291
Historical,690,690,690,690,690,690,690,690,690,690,690,690,690
Horror,92,92,92,92,92,92,92,92,92,92,92,92,92
LGBT,72,72,72,72,72,72,72,72,72,72,72,72,72
Mystery,337,337,337,337,337,337,337,337,337,337,337,337,337
Romance,2083,2083,2083,2083,2083,2083,2083,2083,2083,2083,2083,2083,2083
Science Fiction,220,220,220,220,220,220,220,220,220,220,220,220,220
Thriller & Suspense,56,56,56,56,56,56,56,56,56,56,56,56,56
Young Adult,972,972,972,972,972,972,972,972,972,972,972,972,972

In [96]:
df3['genre_number'] = df3['genre_1']

df3['genre_number'] = df3['genre_number'].replace({"Childrens": '1', "Christian Fiction": '2', "Classics": '3', "Comics, Graphic Novels & Manga": '4', "Erotica": '5', "Fantasy": '6', "Historical": '7', "Horror": '8', "LGBT": '9', "Mystery": '10', "Romance": '11', "Science Fiction": '12', "Thriller & Suspense": '13', "Young Adult": '14'})

In [97]:
df3['genre_number'].unique()

array(['10', '11', '6', '14', '7', '12', '3', '8', '4', '9', '1', '2',
       '5', '13'], dtype=object)

In [98]:
df3.to_csv('df3_final2.csv', index=False)

In [99]:
df3 = pd.read_csv('df3_final2.csv')

In [102]:
df3.groupby(df3['birthplace']).count()

,author_id,author_name,author_page_url,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,period_publication,genre_number
birthplace,,,,,,,,,,,,,,
Africa,37,37,37,37,37,37,37,37,37,37,37,37,37,37
Asia,332,332,332,332,332,332,332,332,332,332,332,332,332,332
Europe,628,628,628,628,628,628,628,628,628,628,628,628,628,628
Latin America,35,35,35,35,35,35,35,35,35,35,35,35,35,35
Oceania,156,156,156,156,156,156,156,156,156,156,156,156,156,156
USA and Canada,3729,3729,3729,3729,3729,3729,3729,3729,3729,3729,3729,3729,3729,3729
Unknown,1524,1524,1524,1524,1524,1524,1524,1524,1524,1524,1524,1524,1524,1524

In [103]:
df3['birthplace_number'] = df3['birthplace']

df3['birthplace_number'] = df3['birthplace_number'].replace({"Africa": '1', "Asia": '2', "Europe": '3', "Latin America": '4', "Oceania": '5', "USA and Canada": '6'})

In [104]:
df3['birthplace_number'].unique()

array(['6', 'Unknown', '3', '4', '5', '1', '2'], dtype=object)

In [106]:
df3['period_publication_number'] = df3['period_publication']

df3['period_publication_number'] = df3['period_publication_number'].replace({"20th century or before": '1', "21st century": '2'})

df3['period_publication_number'].unique()

array(['1', '2'], dtype=object)

In [107]:
df3.to_csv('df3_final3.csv', index=False)

In [108]:
df3 = pd.read_csv('df3_final3.csv')

In [109]:
df3['author_name'] = df3['author_name'].str.strip()
df3['book_title'] = df3['book_title'].str.strip()

In [110]:
df3.head()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,period_publication,genre_number,birthplace_number,period_publication_number
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction,20th century or before,10,6,1
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction,21st century,11,6,2
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Chocolate Pot,Fantasy,Young Adult,326,1988,Fiction,20th century or before,6,6,1
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction,21st century,14,Unknown,2
4,274533,Simone Elkeles,/author/show/274533.Simone_Elkeles,USA and Canada,4.01,https://www.goodreads.com/book/show/544424.Lea...,544424,Leaving Paradise,Young Adult,Romance,303,2007,Fiction,21st century,14,6,2

In [111]:
df3.to_csv('df3_final4.csv', index=False)