In [63]:
import pandas as pd
import numpy as np

df_fiction = pd.read_csv('df3_final2.csv')
df_fiction.head()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,period_publication,genre_number
0,74489,Victoria Thompson,/author/show/74489.Victoria_Thompson,USA and Canada,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,Murder on St. Mark's Place,Mystery,Historical,277,2000,Fiction,20th century or before,10
1,5618190,Mimi Jean Pamfiloff,/author/show/5618190.Mimi_Jean_Pamfiloff,USA and Canada,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,Tailored for Trouble,Romance,Contemporary,354,2016,Fiction,21st century,11
2,36122,Patricia C. Wrede,/author/show/36122.Patricia_C_Wrede,USA and Canada,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,Sorcery & Cecelia: or The Enchanted Cho...,Fantasy,Young Adult,326,1988,Fiction,20th century or before,6
3,4833990,Jillian Dodd,/author/show/4833990.Jillian_Dodd,Unknown,3.95,https://www.goodreads.com/book/show/34804503-s...,34804503,Stalk Me,Young Adult,Romance,327,2012,Fiction,21st century,14
4,274533,Simone Elkeles,/author/show/274533.Simone_Elkeles,USA and Canada,4.01,https://www.goodreads.com/book/show/544424.Lea...,544424,Leaving Paradise,Young Adult,Romance,303,2007,Fiction,21st century,14

In [41]:
df_nonfiction = pd.read_csv('df2_final4.csv')
df_nonfiction.head()

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,genre_number
0,7956,Mary Roach,/author/show/7956.Mary_Roach,USA and Canada,3.84,https://www.goodreads.com/book/show/5981308-bonk,5981308,Bonk: The Curious Coupling of Science a...,Science,Science,319,2008,Nonfiction,7
1,925098,Jennifer Storm,/author/show/925098.Jennifer_Storm,Unknown,3.72,https://www.goodreads.com/book/show/2034321.Bl...,2034321,Blackout Girl: Growing Up and Drying Ou...,Biography & Autobiography,Nonfiction,280,2008,Nonfiction,2
2,3275,Jeannette Walls,/author/show/3275.Jeannette_Walls,USA and Canada,4.26,https://www.goodreads.com/book/show/7445.The_G...,7445,The Glass Castle,Biography & Autobiography,Autobiography,288,2005,Nonfiction,2
3,11679,Elizabeth Gilbert,/author/show/11679.Elizabeth_Gilbert,USA and Canada,3.53,https://www.goodreads.com/book/show/19501.Eat_...,19501,"Eat, Pray, Love",Biography & Autobiography,Autobiography,334,2006,Nonfiction,2
4,3720,Anne Frank,/author/show/3720.Anne_Frank,Europe,4.12,https://www.goodreads.com/book/show/48855.The_...,48855,The Diary of a Young Girl,Biography & Autobiography,Classics,304,1947,Nonfiction,2

In [75]:
def fiction_nonfiction():
    input1 = input("""Do you want to read a fictional or a nonfictional book?
Type 'f' for fictional or 'nf' for nonfictional. """)
    if input1.lower() != 'f' and input1 != 'nf':
        input1 = input("Please, type 'f' for fictional or 'nf' for nonfictional books. ")
    else:
        return input1

In [76]:
fiction_nonfiction()

Do you want to read a fictional or a nonfictional book?
Type 'f' for fictional or 'nf' for nonfictional. f

'f'

In [77]:
def non_fiction():
    input2 = input(""" Which type of nonfictional book do you want to read? Type:
    1 for Animals,
    2 for Biography & Autobiography,
    3 for Feminism,
    4 for Food & Drinks,
    5 for History,
    6 for Religion & Spirituality,
    7 for Science,
    8 for Self Help,
    9 for Travel or
    10 for Writing. """)
    if int(input2) not in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        input2 = input(""" Please, type
    1 for Animals,
    2 for Biography & Autobiography,
    3 for Feminism,
    4 for Food & Drinks,
    5 for History,
    6 for Religion & Spirituality,
    7 for Science,
    8 for Self Help,
    9 for Travel or
    10 for Writing. """)
    return input2

In [59]:
non_fiction()

 Which type of nonfictional book do you want to read? Type
                   1 for Animals,
                   2 for Biography & Autobiography,
                   3 for Feminism,
                   4 for Food & Drinks,
                   5 for History',
                   6 for 'Religion & Spirituality,
                   7 for 'Science',
                   8 for 'Self Help',
                   9 for 'Travel' or
                   10 for Writing. 6

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,genre_number
380,6951311,Phylline Phillips,/author/show/6951311.Phylline_Phillips,Unknown,4.69,https://www.goodreads.com/book/show/17408302-h...,17408302,Homeward Bound: A Journey Of Faith,Religion & Spirituality,Inspirational,46,2013,Nonfiction,6

In [78]:
def fiction():
    input3 = input(""" Which kind of fictional book do you want to read? Type:
    1 for Childrens,
    2 for Christian Fiction,
    3 for Classics,
    4 for Comics, Graphic Novels & Manga,
    5 for Erotica,
    6 for Fantasy,
    7 for Historical,
    8 for Horror,
    9 for LGBT,
    10 for Mystery,
    11 for Romance,
    12 for Science Fiction,
    13 for Thriller & Suspense or 
    14 for Young Adult.""")
    if int(input3) not in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]:
        input3 = input(""" Please, type
    1 for Childrens,
    2 for Christian Fiction,
    3 for Classics,
    4 for Comics, Graphic Novels & Manga,
    5 for Erotica,
    6 for Fantasy,
    7 for Historical,
    8 for Horror,
    9 for LGBT,
    10 for Mystery,
    11 for Romance,
    12 for Science Fiction,
    13 for Thriller & Suspense or 
    14 for Young Adult. """)
    return input3

In [65]:
fiction()

 Which kind of fictional book do you want to read? Type
                   1 for Childrens,
                   2 for Christian Fiction,
                   3 for Classics,
                   4 for Comics, Graphic Novels & Manga,
                   5 for Erotica,
                   6 for Fantasy,
                   7 for Historical,
                   8 for Horror,
                   9 for LGBT,
                   10 for Mystery,
                   11 for Romance,
                   12 for Science Fiction,
                   13 for Thriller & Suspense or
                   14 for Young Adult.6

'6'

In [61]:
def system():
    input1 = fiction_nonfiction()
    if input1 == 'nf':
        input2 = int(non_fiction())
        genre = df_nonfiction.loc[df_nonfiction['genre_number'] == input2]
        book_recommendation = genre.sample(n=1)
        return book_recommendation
    else:
        print('Fiction')

In [62]:
system()

Do you want to read a fictional or a nonfictional book? Type 'f' for fictional or 'nf' for nonfictional. nf
 Which type of nonfictional book do you want to read? Type
                   1 for Animals,
                   2 for Biography & Autobiography,
                   3 for Feminism,
                   4 for Food & Drinks,
                   5 for History',
                   6 for 'Religion & Spirituality,
                   7 for 'Science',
                   8 for 'Self Help',
                   9 for 'Travel' or
                   10 for Writing. 5

,author_id,author_name,author_page_url,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,pages,year_publication,fiction_nonfiction,genre_number
149,101131,Amity Shlaes,/author/show/101131.Amity_Shlaes,Unknown,3.91,https://www.goodreads.com/book/show/1289617.Th...,1289617,The Forgotten Man: A New History of the...,History,Nonfiction,390,2007,Nonfiction,5